#! /bin/bash

# DELETE PREVIOUS STOW
stow -D .

# SOURCE COLORS
. "./.shell/colors"

# MAKE DIRECTORIES
mkdir -pv "$HOME/.local/bin"

# GET ALL DIRS IN .config
CONFIG_FOLDERS=( )
for dir in .config/*
do
	CONFIG_FOLDERS+=( "$HOME/.config/"${dir#$".config"\/} )
done

mkdir -pv ${CONFIG_FOLDERS[@]}

# CHECK IF OH-MY-ZSH IS INSTALLED
if [ ! -d "$HOME/.oh-my-zsh" ]; then
	echo -e "${F_BOLD%}${F_C_YELLOW}WARNING:${NO_FORMAT} oh-my-zsh is not installed, install it here: ${F_C_PURPLE}https://ohmyz.sh/#install${NO_FORMAT}\n"
fi

# STOW FILES
stow -R .